### ISSUE TITLE
CLI commands fail after updating to 3.1.4 of Lando.

### ISSUE THREAD

**Issue by seantwalsh** [lando/cli#10]
Thinking it makes more sense to add this to lando/cli vs. lando/lando as it seems cli related. 

After updating to Lando 3.1.4 I get the following error whenever I type a lando cli command. I tried completely removing Lando and it's config and still no luck. Thinking this is an edge case due to breaking out the cli from the other repo as I haven't seen anyone else with a similar issue yet. Any help is greatly appreciated!!!

`Unhandled rejection TypeError: Cannot create property 'key' on string 'a'
    at /snapshot/lando/build/cli/integrations/lando-acquia/lib/utils.js
    at /snapshot/lando/build/cli/node_modules/lodash/lodash.js:4943:15
    at Function.forEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9410:14)
    at Object.getHostKeys (/snapshot/lando/build/cli/integrations/lando-acquia/lib/utils.js)
    at mergeKeys (/snapshot/lando/build/cli/integrations/lando-acquia/recipes/acquia/init.js)
    at Object.options (/snapshot/lando/build/cli/integrations/lando-acquia/recipes/acquia/init.js)
    at /snapshot/lando/build/cli/plugins/lando-recipes/lib/options.js
    at arrayEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9410:14)
    at Object.getConfigOptions (/snapshot/lando/build/cli/plugins/lando-recipes/lib/options.js)
    at /snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js
    at /snapshot/lando/build/cli/lib/lando.js
From previous event:
    at processImmediate (internal/timers.js:456:21)`

**Comment by owenbush** [comment]
This feels very similar to the issue I raised earlier today (I raised it against lando/lando as it didn't seem like there were issues being tracked here). 

lando/lando#3058

If I had to take a guess based on what you have here and what I saw for the Lagoon integration, it will be related to not having any keys set up yet, and Lando not initializing the array of keys properly.

For example, a brief look at `integrations/lando-acquia/recipes/acquia/init.js` on line 17 I see:

`const mergeKeys = (home, keys = []) => utils.sortKeys(utils.getHostKeys(home), keys);`

If there are no keys yet in `utils.getHostKeys(home)` then `sortKeys()` will fail to work properly.

If you compare that to `integrations/lando-acquia/app.js` on line 47 you can see that an attempt has been made there to initialize an empty array if no keys exist, but it doesn't seem like this has been done in init.js

`app.hostKeys = utils.getHostKeys(lando.config.home) || [];`

This is very similar to what I had to fix in Lagoon's integration.

**Comment by seantwalsh** [comment]
@owenbush thanks for linking to that issue and providing some more info. I wonder if this is ultimately caused by me having changed the key loading behavior per https://docs.lando.dev/config/ssh.html as I used to get the too many keys warning. However, I would think that a completely clean install would work and it didn't unless something was still lingering somewhere on my system.

**Comment by seantwalsh** [comment]
Another user reported the issue yesterday in Slack. Like me they ended up downgrading to Lando 3.0.26.

**Comment by seantwalsh** [comment]
Not sure why, but I'm was able to updated to 3.3.0 and am not having any issues so closing this out.
