### ISSUE TITLE
Support Node 18

### ISSUE THREAD

**Issue by pschoffer** [lando/cli#148]
More info in the PR: https://github.com/lando/cli/pull/147

**Comment by dustinleblanc** [comment]
@pschoffer Thanks for the PR! I do think support for the latest node is great, but Lando has always stuck to LTS Node, so it isn't really necessary. Up to @pirog whether this is something he wants to pursue, but in general, I assume Lando will stick to LTS. Were there any specific features of Node 18 that you thought would significantly benefit Lando or were things you needed for work you were doing? Note that the project also contains a [.node-version](https://github.com/lando/cli/blob/main/.node-version) file that specifies the supported version. Now that I look at it, it _is_ out of sync with LTS...

**Comment by chrillep** [comment]
ref:
- https://github.com/lando/node/issues/24

**Comment by reynoldsalec** [comment]
Support added as of Lando Node [v0.8.0](https://github.com/lando/node/releases/tag/v0.8.0)
