### ISSUE TITLE
Docker-compose version fails on darwin 21.5.0

### ISSUE THREAD

**Issue by pschoffer** [lando/cli#153]
The current implementation tries to do:
```
defaults read /Applications/Docker.app/Contents/Info.plist ComposeVersion
```
https://github.com/lando/cli/blob/e2d84d76c33175ac47e356997679a6b8524d9665/lib/daemon.js#L182

However, there is no key ComposeVersion (nor `EngineVersion`) in the defaults object on `darwin 21.5.0` (works fine on `darwin 20.x.x`).

The `linux` variant - `docker-compose version --short` , seems to work on `darwin` too. 

Is there a reason we are using the `defaults` instead on darwin?

**Comment by reynoldsalec** [comment]
@pschoffer I believe Lando no longer does this; now that we've integrated Docker Compose v2 support in [v3.20.0](https://github.com/lando/core/releases/tag/v3.20.0) I think this issue is resolved.
