### ISSUE TITLE
Crash handler does not respect --yes

### ISSUE THREAD

**Issue by AaronFeledy** [lando/cli#242]
If an error occurs during `lando setup -y` the user is shown a CRASH message followed by a prompt asking if they'd like to send an error report. When running this as part of a scripted process, it may not be desirable, or even possible for the user to respond, potentially leading to a hung process. The error handler should respect the `-y` and it should not prompt the user.

**Comment by AaronFeledy** [comment]
Or if privacy might be a concern here, `lando setup` could disable the error reporting during non-interactive execution if the user has not yet had the opportunity to respond to this prompt.

**Comment by pirog** [comment]
@AaronFeledy got a PR for this https://github.com/lando/cli/pull/247, let me know what you think
