### ISSUE TITLE
Add option to disable unsupported version banner

### ISSUE THREAD

**Issue by hailwood** [lando/cli#267]
> Using an untested version of DOCKER ENGINE
    We have not tested version 26.1.1 yet so congrats on being a pioneer!
    Seriously though, this is usually not an issue but be mindful that you
    are in uncharted territory. If you encounter an issue we recomend
    you downgrade to something <=26.0.0
    
I'd love a config option to say "I know" and hide the banner.

**Comment by pirog** [comment]
We probably arent going to do this for Lando 3. 

That said I would note that these checks are based on values in `lando config --path dockerSupportedVersions` eg you can modify these in your global lando config to suppress the checks

**Comment by hailwood** [comment]
Perfect,

That works for me. Thanks @pirog
