### ISSUE TITLE
Keys never loaded

### ISSUE THREAD

**Issue by sonuku** [lando/cli#34]
https://github.com/lando/cli/blob/53eaddc11ce44fe3b38708f4ac3d5275b2c931c4/plugins/lando-core/scripts/load-keys.sh#L93

Should this be a lowercase L?

https://linux.die.net/man/1/grep
`-L, --files-without-match`
`-l, --files-with-matches`

Uppercase L means it never adds the files from the candidates?

Locally changing to a `-l` fixes and loads up keys.
Without it, nothing.

Without ssh keys, cant use a lot of the junk.

**Comment by sonuku** [comment]
Or is it that

```
# Go through and validate our candidates
for SSH_CANDIDATE in "${SSH_CANDIDATES[@]}"; do
  lando_debug "Ensuring permissions and ownership of $SSH_CANDIDATE..."
  chown -R $LANDO_WEBROOT_USER:$GROUP "$SSH_CANDIDATE"
  chmod 600 "$SSH_CANDIDATE"
  lando_debug "Checking whether $SSH_CANDIDATE is a private key..."
  if grep -L "PRIVATE KEY" "$SSH_CANDIDATE" &> /dev/null; then
    if command -v ssh-keygen >/dev/null 2>&1; then
      lando_debug "Checking whether $SSH_CANDIDATE is formatted correctly..."
      if ssh-keygen -l -f "$SSH_CANDIDATE" &> /dev/null; then
        SSH_KEYS+=("$SSH_CANDIDATE")
        SSH_IDENTITIES+=("  IdentityFile \"$SSH_CANDIDATE\"")
      elif ssh-keygen -y -e -f "$SSH_CANDIDATE" &> /dev/null; then
        SSH_KEYS+=("$SSH_CANDIDATE")
        SSH_IDENTITIES+=("  IdentityFile \"$SSH_CANDIDATE\"")
      fi
    else
      SSH_KEYS+=($SSH_CANDIDATE)
      SSH_IDENTITIES+=("  IdentityFile \"$SSH_CANDIDATE\"")
    fi
  fi
done
```


should be

```
# Go through and validate our candidates
for SSH_CANDIDATE in "${SSH_CANDIDATES[@]}"; do
  lando_debug "Ensuring permissions and ownership of $SSH_CANDIDATE..."
  chown -R $LANDO_WEBROOT_USER:$GROUP "$SSH_CANDIDATE"
  chmod 600 "$SSH_CANDIDATE"
  lando_debug "Checking whether $SSH_CANDIDATE is a private key..."
  if grep -L "PRIVATE KEY" "$SSH_CANDIDATE" &> /dev/null; then
    if command -v ssh-keygen >/dev/null 2>&1; then
      lando_debug "Checking whether $SSH_CANDIDATE is formatted correctly..."
      if ssh-keygen -l -f "$SSH_CANDIDATE" &> /dev/null; then
        SSH_KEYS+=("$SSH_CANDIDATE")
        SSH_IDENTITIES+=("  IdentityFile \"$SSH_CANDIDATE\"")
      elif ssh-keygen -y -e -f "$SSH_CANDIDATE" &> /dev/null; then
        SSH_KEYS+=("$SSH_CANDIDATE")
        SSH_IDENTITIES+=("  IdentityFile \"$SSH_CANDIDATE\"")
      fi
    fi
  else
    SSH_KEYS+=($SSH_CANDIDATE)
    SSH_IDENTITIES+=("  IdentityFile \"$SSH_CANDIDATE\"")
  fi
done
```

It looks like youre checking for valid keys (maybe encrypted? i dont know) but then never actually allowing the non password protected keys through?

Either way, I cant get anything to work when trying to run a `lando pull` unless a key loads.

**Comment by sonuku** [comment]
Possibly related to https://github.com/lando/lando/issues/3091

`$ lando ssh -s cli -c "ls -al /lando/keys"`

```
...
-rw-------  1 user dialout 1811 Sep  9 06:44 lagoon-32ee3a15-b507-4591-902e-e848c300b924
```

`$ lando ssh -s cli -c "cat /etc/ssh/ssh_config"`

```
Host *
  User "al"
  StrictHostKeyChecking no
  UserKnownHostsFile=/dev/null
  LogLevel=FATAL
```

**Comment by sonuku** [comment]
So big goose hunt on with @pirog over slack. We may have found an underlying cause for the inconsistencies. This looks like its due to a BusyBox flavour of grep.

`grep -L "PRIVATE KEY" /lando/keys/a-random-key` returns nothing. No status code 0.

Docker image `uselagoon/php-7.3-cli-drupal` if you go up the chain of FROM's is based off of `FROM alpine:3.14`

To upgrade grep to a gnu install, and make it work, in your Dockerfile you could add:

```dockerfile
RUN apk add --no-cache --upgrade grep
```

It would appear there is some inconsistencies between the greps out there.
But thats not really a fix to a problem. Alpine will continue to use busybox grep, this continues to pop-up as a problem.

I wonder if something like busybox detection might be the answer here? Minimal impact.
```sh
if grep --help 2>&1 | grep -q -i "busybox"; then
  ... this greps crazy shit, set a diff condition
fi
```

**Comment by pirog** [comment]
@sonuku to add more fun to this we get status code `0` on `alpine:3.13` so i'm guessing this started showing up when Lagoon bumped up to `alpine:3.14`.

All said and now that we understand the issue here i think we should just switch over to the `-l` from `-L` as you initially recommended. That seems like the option we want anyway and _THEORETICALLY_ it should produce the same behavior in our none `alpine:3.14` images.

**Comment by sonuku** [comment]
Yeah seems depending on your grep version (even gnu) `-L` is a bit fucky. Pasted in the bug reports in above comment.

**Comment by tobybellwood** [comment]
hihi - circling the square here - wherever possible we try to avoid overwriting the busybox packages, just to avoid potential complications.  Thanks for digging into this @sonuku!
