### ISSUE TITLE
Update Backdrop's PHP version

### ISSUE THREAD

**Issue by BWPanda** [lando/cli#83]
Backdrop's recipe is using PHP version 7.2:

https://github.com/lando/cli/blob/7fae873dcda2ef0878bf9a5ea52962dad732b015/plugins/lando-recipes/recipes/backdrop/builder.js#L53 

Lando is telling me this is a legacy version:

> php version 7.2 is a legacy version! We recommend upgrading.

Can we update that please?

**Comment by labboy0276** [comment]
OK, we can update it to 7.4

**Comment by labboy0276** [comment]
OK @BWPanda I changed the default php version to 7.4.  I will be released in the next version of lando.

In the interim, if you want that message to go away, please set your php to 7.3 or higher via https://docs.lando.dev/config/backdrop.html#configuration
